version: '3.8'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - '9090:9090'
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.external-url=http://localhost:9090'
  #    extra_hosts:
  #      - 'host.docker.internal:4000'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - '5000:3000'
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin

  dockerhost:
    image: qoomon/docker-host
    cap_add: ['NET_ADMIN', 'NET_RAW']
    mem_limit: 8M
    restart: on-failure
  tcp_message_emitter:
    depends_on: [dockerhost]
    image: alpine
    command: ['sh', '-c', "while :; do date; sleep 1; done | nc 'docker-host' 2323 -v"]
  udp_message_emitter:
    depends_on: [dockerhost]
    image: alpine
    command: ['sh', '-c', "while :; do date; sleep 1; done | nc 'docker-host' 5353 -u -v"]
