[package]
name = "backend"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
readme = "README.md"


[dependencies]
actix-web = "3.3.2"
actix-files = "0.5.0"
clap = "3.0.0-beta.4"
serde_json = "1.0.68"
serde = "1.0.130"
actix-cors = "0.5.4"

sandbox = { path = "../sandbox" }

[dev-dependencies]
actix-rt = "2.3.0"

[features]
docker_tests = []
