[package]
name = "backend"
version = "0.1.0"
edition = "2021"
authors = ["Achim Schneider <achim@parity.io>"]
license = "Apache-2.0"
readme = "README.md"

[dependencies]
actix-web = "4.2.1"
actix-web-prom = "0.6.0"
actix-files = "0.6.2"
clap = "3.0.0-beta.4"
serde_json = "1.0.91"
serde = "1.0.152"
actix-cors = "0.6.4"
ts-rs = { git = "https://github.com/Aleph-Alpha/ts-rs", branch = "main", features = [
    "serde-compat",
] }
futures = "0.3.25"
hubcaps = "0.6.2"
tokio-compat-02 = "0.2.0"

sandbox = { path = "../sandbox" }

[dev-dependencies]
actix-rt = "2.7.0"

