name: Compiler_Docker_Push

on:
  workflow_run:
    workflows: ['Compiler_Docker']
    types:
      - completed

jobs:
  push:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Tag Docker image
        if: ${{ github.repository == 'paritytech/ink-playground' && github.ref == 'refs/heads/main' }}
        run: docker tag ink-backend:latest ${{ secrets.DOCKER_USER_NAME }}/ink-backend

      - name: Push Docker image
        if: ${{ github.repository == 'paritytech/ink-playground' && github.ref == 'refs/heads/main' }}
        run: docker push ${{ secrets.DOCKER_USER_NAME }}/ink-backend
