name: Compiler_Docker

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3

      - name: Compare Cargo.toml files
        run: diff ./compiler/Cargo.toml ./crates/contract/Cargo.toml

      - name: Build docker
        run: docker build -f Dockerfile.compiler --tag ink-backend .

      - name: Login to DockerHub
        if: github.ref == 'refs/heads/main' && github.repository == 'paritytech/ink-playground'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Tag Docker image
        if: github.ref == 'refs/heads/main' && github.repository == 'paritytech/ink-playground'
        run: docker tag ink-backend:latest ${{ secrets.DOCKER_USER_NAME }}/ink-backend

      - name: Push Docker image
        if: github.ref == 'refs/heads/main' && github.repository == 'paritytech/ink-playground'
        run: docker push ${{ secrets.DOCKER_USER_NAME }}/ink-backend
