name: Docker

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3

      - name: get Sysbox
        run: wget https://downloads.nestybox.com/sysbox/releases/v0.5.2/sysbox-ce_0.5.2-0.linux_amd64.deb

      - name: Install Sysbox
        run: sudo apt-get install ./sysbox-ce_0.5.2-0.linux_amd64.deb

      - name: Configure Sysbox runtime
        run: sudo cp sysbox/daemon.json /etc/docker/daemon.json

      - name: Restart docker service
        run: sudo systemctl restart docker.service

      - name: Build docker
        run: make docker-buildkit
        env:
          DOCKER_USER_NAME: ${{ secrets.DOCKER_USER_NAME }}

      - name: Tag Docker image
        run: docker tag ${{ secrets.DOCKER_USER_NAME }}/ink-playground:latest ink-playground

      - name: Run docker
        run: make docker-run-detach
        env:
          DOCKER_PORT: 4000

      - name: Sleep for 120s, allow Docker image to boot up
        uses: juliangruber/sleep-action@v1
        with:
          time: 120s

      - name: Install docker-tests
        run: yarn workspace docker-tests install

      - name: Test docker
        run: make docker-test
        env:
          DOCKER_PORT: 4000

      - name: docker log
        if: always()
        run: make docker-log

      - name: Login to DockerHub
        if: github.ref == 'refs/heads/main' && github.repository == 'paritytech/ink-playground'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Push Docker image
        if: github.ref == 'refs/heads/main' && github.repository == 'paritytech/ink-playground'
        run: docker push ${{ secrets.DOCKER_USER_NAME }}/ink-playground

      - name: Invoke deployment hook
        if: github.ref == 'refs/heads/main' && github.repository == 'paritytech/ink-playground'
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL }}/redeploy
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
